#!/bin/bash
# Gmail Configuration Guide for Jenkins
# Follow these steps to enable email notifications

echo "=========================================="
echo "Gmail Configuration for Jenkins"
echo "=========================================="
echo ""

echo "Step 1: Get Gmail App Password"
echo "-------------------------------"
echo "1. Go to: https://myaccount.google.com/security"
echo "2. Enable '2-Step Verification' (if not already enabled)"
echo "3. Go to: https://myaccount.google.com/apppasswords"
echo "4. Select:"
echo "   - App: Mail"
echo "   - Device: Other (type 'Jenkins')"
echo "5. Click 'Generate'"
echo "6. Copy the 16-character password (no spaces)"
echo ""
echo "⚠️  IMPORTANT: Save this password - you'll need it in Jenkins!"
echo ""

echo "Step 2: Configure Jenkins Email"
echo "--------------------------------"
echo "In Jenkins (http://13.53.174.119:8080):"
echo ""
echo "A. Extended E-mail Notification:"
echo "   Manage Jenkins → System → Extended E-mail Notification"
echo ""
echo "   SMTP server: smtp.gmail.com"
echo "   SMTP Port: 465"
echo "   Advanced:"
echo "     ✅ Use SSL"
echo "     Credentials → Add → Jenkins"
echo "       Kind: Username with password"
echo "       Username: your-email@gmail.com"
echo "       Password: [paste 16-char app password]"
echo "       ID: gmail-credentials"
echo "       Description: Gmail SMTP"
echo "     Select the credential you just created"
echo "   Default Content Type: HTML (text/html)"
echo ""
echo "B. E-mail Notification:"
echo "   Manage Jenkins → System → E-mail Notification"
echo ""
echo "   SMTP server: smtp.gmail.com"
echo "   Advanced:"
echo "     ✅ Use SMTP Authentication"
echo "     User Name: your-email@gmail.com"
echo "     Password: [paste 16-char app password]"
echo "     ✅ Use SSL"
echo "     SMTP Port: 465"
echo "   Test configuration:"
echo "     Test e-mail recipient: your-email@gmail.com"
echo "     Click 'Test configuration'"
echo "     ✅ Should say 'Email was successfully sent'"
echo ""
echo "C. Click Save"
echo ""

echo "Step 3: Verify Jenkinsfile Email Configuration"
echo "-----------------------------------------------"
echo "Your Jenkinsfile already has email configuration in the 'post' section."
echo "It will send emails to the Git committer's email address."
echo ""

echo "Step 4: Test Email Notification"
echo "--------------------------------"
echo "After configuring email in Jenkins:"
echo "1. Trigger a build (push code or click Build Now)"
echo "2. Check your email inbox"
echo "3. Should receive email with build results"
echo ""

echo "=========================================="
echo "Quick Settings Summary"
echo "=========================================="
echo ""
echo "SMTP Server: smtp.gmail.com"
echo "SMTP Port: 465"
echo "Use SSL: Yes"
echo "Username: your-email@gmail.com"
echo "Password: [16-char app password from Google]"
echo ""
echo "Alternative SMTP Settings (if 465 doesn't work):"
echo "SMTP Server: smtp.gmail.com"
echo "SMTP Port: 587"
echo "Use TLS: Yes"
echo ""
